package ExceptionHandling;

public class Q2 {

	public static void main(String[] args) {
       int a=10;
       int b=0;
       
		try{
		double c =a/b;	
		}
		catch(Exception e){
			System.out.println("catch is handling");
		}
		
			
		
		
		
}
}
